name: pizza - infrastructure delivery pipeline

on:
  push:
    branches: [ 04_pipeline ]
  pull_request:
    branches: [ 04_pipeline ]

jobs:
  test-unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      working-directory: .
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with autopep8
      run: |
        autopep8 -r -d --exit-code .
    - name: Run unit tests
      run: |
        pytest test/unit/

  test-contract:
    needs: test-unit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      working-directory: .
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with autopep8
      run: |
        autopep8 -r -d --exit-code .
    - name: Run contract tests
      run: |
        pytest test/contract/


  deploy-dev:
    needs: test-contract
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.5
    - name: Deploy infrastructure to dev
      env:
        CLOUDSDK_CORE_PROJECT: ${{ secrets.CLOUDSDK_CORE_PROJECT }}
        GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
      run: |
        echo $GOOGLE_SERVICE_ACCOUNT_JSON  | base64 -d > $GOOGLE_APPLICATION_CREDENTIALS
        terraform init
        terraform apply -auto-approve -var-file=dev.tfvars